routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function(){
    return view('welcome');
})->name('welcome');

Route::get('/tentang', 'TentangController@index')->name('tentang');

Route::get('/kontak', 'KontakController@index')->name('kontak');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/home/retrieve', 'HomeController@retrieve')->name('retrieve');

    /*password*/
    Route::name('password.')->group(function() {
        Route::get('/password/{id}/edit', 'PasswordController@edit')->name('edit');
        Route::patch('/password/{id}', 'PasswordController@update')->name('update');
    });

    /*profil*/
    Route::name('profile.')->group(function() {
        Route::get('/profile', 'ProfileController@index')->name('index');
        Route::patch('/profile/{id}', 'ProfileController@update')->name('update');
    });

    /*mahasiswa*/
    Route::name('mahasiswa.')->group(function() {
        Route::get('/mahasiswa', 'MahasiswaController@index')->name('index');
        Route::get('/mahasiswa/create', 'MahasiswaController@create')->name('create');
        Route::post('/mahasiswa', 'MahasiswaController@store')->name('store');
        Route::get('/mahasiswa/{id}', 'MahasiswaController@show')->name('show');
        Route::get('/mahasiswa/{id}/edit', 'MahasiswaController@edit')->name('edit');
        Route::patch('/mahasiswa/{id}', 'MahasiswaController@update')->name('update');
        Route::delete('/mahasiswa/{id}', 'MahasiswaController@destroy')->name('destroy');  
    });

    /*dosen*/
    Route::name('dosen.')->group(function() {
        Route::get('/dosen', 'DosenController@index')->name('index');
        Route::get('/dosen/create', 'DosenController@create')->name('create');
        Route::post('/dosen', 'DosenController@store')->name('store');
        Route::get('/dosen/{id}', 'DosenController@show')->name('show');
        Route::get('/dosen/{id}/edit', 'DosenController@edit')->name('edit');
        Route::patch('/dosen/{id}', 'DosenController@update')->name('update');
        Route::delete('/dosen/{id}', 'DosenController@destroy')->name('destroy');
    });

    /*kelas*/
    Route::name('kelas.')->group(function() {
        Route::get('/kelas', 'KelasController@index')->name('index');
        Route::get('/kelas/list', 'KelasController@kelas_list')->name('list');
        Route::get('/kelas/list/ajax', 'KelasController@ajax_kelas_list')->name('ajax_list');
        Route::get('/kelas/join', 'KelasController@kelas_join')->name('join');
        Route::get('/kelas/join/ajax', 'KelasController@ajax_kelas_join')->name('ajax_join');
        Route::post('/kelas/join', 'KelasController@token_handler')->name('token_handler');
        Route::get('/kelas/{id}/desc', 'KelasController@desc')->name('desc');
        Route::get('/kelas/{id}/desc/ajax', 'KelasController@ajax_desc')->name('ajax_desc');
        Route::get('/kelas/{id}/peserta', 'KelasController@peserta')->name('peserta');
        Route::get('/kelas/{id}/peserta/ajax', 'KelasController@ajax_peserta')->name('ajax_peserta');
        Route::patch('/kelas/{kelas_id}/peserta/{user_id}', 'KelasController@kick_peserta')->name('kick_peserta');
        Route::get('/kelas/create', 'KelasController@create')->name('create');
        Route::post('/kelas', 'KelasController@store')->name('store');
        Route::get('/kelas/{id}', 'KelasController@show')->name('show');
        Route::get('/kelas/{id}/edit', 'KelasController@edit')->name('edit');
        Route::patch('/kelas/{id}', 'KelasController@update')->name('update');
        Route::delete('/kelas/{id}', 'KelasController@destroy')->name('destroy');
        Route::post('/kelas/status', 'KelasController@status')->name('status');
    });

    Route::name('session.')->group(function() {
        Route::get('/kelas/{id}/session', 'SessionController@index')->name('index');
        Route::get('/kelas/{id}/session/ajax', 'SessionController@ajax_session')->name('ajax_session');
        Route::get('/kelas/{id}/session/create', 'SessionController@create')->name('create');
        Route::post('/kelas/{id}/session', 'SessionController@store')->name('store');
        Route::get('/kelas/{id}/session/{session_of}', 'SessionController@show')->name('show');
        Route::get('/kelas/{id}/session/{session_of}/edit', 'SessionController@edit')->name('edit');
        Route::patch('/kelas/{id}/session/{session_of}', 'SessionController@update')->name('update');
        Route::delete('/kelas/{id}/session/{session_of}', 'SessionController@destroy')->name('destroy');
        Route::post('/kelas/session/status', 'SessionController@status')->name('status');
    });

    Route::name('posting.')->group(function() {
        Route::post('/kelas/{id}/session/{session_of}/posting', 'PostingController@store')->name('store');
        Route::delete('/kelas/session/posting/{id}', 'PostingController@destroy')->name('destroy');
    });
    
    Route::name('comment.')->group(function() {
        Route::post('/kelas/session/posting/{posting_id}/comment', 'CommentController@store')->name('store');
        Route::delete('/kelas/session/posting/comment/{comment_id}', 'CommentController@destroy')->name('destroy');
    });

    Route::name('tugas_comment.')->group(function() {
        Route::post('/kelas/session/tugas/{tugas_id}/comment', 'TugasCommentController@store')->name('store');
        Route::delete('/kelas/session/tugas/comment/{comment_id}', 'TugasCommentController@destroy')->name('destroy');
    });

    Route::name('absent.')->group(function() {
        Route::get('/kelas/{kelas_id}/session/{session_of}/absent', 'AbsentController@index')->name('index');
        Route::post('/kelas/{kelas_id}/session/{session_of}/absent', 'AbsentController@store')->name('store');
    });

    Route::name('tugas.')->group(function() {
        Route::get('/kelas/{kelas_id}/session/{session_of}/tugas', 'TugasController@index')->name('index');
        Route::post('/kelas/{kelas_id}/session/{session_of}/tugas', 'TugasController@store')->name('store');
        Route::delete('/kelas/session/tugas/{id}', 'TugasController@destroy')->name('destroy');
    });

    /*modul*/
    Route::name('modul.')->group(function() {
        Route::get('/modul', 'ModulController@index')->name('index');
        Route::get('/modul/{slug}/desc', 'ModulController@desc')->name('desc');
        Route::get('/modul/{slug}/desc/ajax', 'ModulController@ajax_desc')->name('ajax_desc');
        Route::get('/modul/create', 'ModulController@create')->name('create');
        Route::post('/modul', 'ModulController@store')->name('store');
        Route::get('/modul/{slug}', 'ModulController@show')->name('show');
        Route::get('/modul/{slug}/edit', 'ModulController@edit')->name('edit');
        Route::patch('/modul/{id}', 'ModulController@update')->name('update');
        Route::delete('/modul/{id}', 'ModulController@destroy')->name('destroy');
        Route::post('/modul/status', 'ModulController@status')->name('status');
    });

    /*lecture*/
    Route::name('lecture.')->group(function() {
        Route::get('/modul/{slug}/lecture', 'LectureController@index')->name('index');
        Route::get('/modul/{slug}/lecture/ajax', 'LectureController@ajax_lecture')->name('ajax_lecture');
        Route::get('/modul/{slug}/lecture/create', 'LectureController@create')->name('create');
        Route::post('/modul/{slug}/lecture', 'LectureController@store')->name('store');
        Route::get('/modul/{slug}/lecture/{urutan}', 'LectureController@show')->name('show');
        Route::get('/modul/{slug}/lecture/{urutan}/edit', 'LectureController@edit')->name('edit');
        Route::patch('/modul/{slug}/lecture/{urutan}', 'LectureController@update')->name('update');
        Route::delete('/modul/{slug}/lecture/{urutan}', 'LectureController@destroy')->name('destroy');
        Route::post('/modul/lecture/status', 'LectureController@status')->name('status');
    });

    /*pencarian*/
    Route::get('/pencarian', 'PencarianController@index')->name('pencarian');
});

Route::get('/clear-cache', function () {
    $exitCode =
        Artisan::call('config:clear');
    $exitCode =
        Artisan::call('cache:clear');
    $exitCode =
        Artisan::call('config:cache');
    return 'Cache cleared!';
});

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

/* IMPORT CLASSES */

/* IMPORT MODEL */
use App\Modul;
use App\Lecture;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

     /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
     public function index()
    {
        $modul = Modul::withCount('lectures')->where('status', '1')->take(6)->get();
        $sum_data = Modul::count();
        $search = '';
        return view('home', compact('modul', 'sum_data', 'search'))->with('title', 'Beranda');
    }

    public function retrieve(Request $request)
    {
        /*ajax fetching*/
        $taker = $request->get('taker');
        $sum_data = $request->get('sumData');
        /*end*/

        if ($taker > $sum_data) {
            $taker = $sum_data;
        }

        /*check apakah ada data yang di parse lewat uri*/
        $search = $request->get('searchData');
        /*end*/

        $modul = Modul::withCount('lectures')->where('status', '1')->where('title', 'like', "%" . $search . "%")
            ->orWhere('status', '1')->where('level', 'like', "%" . $search . "%")
            ->orWhere('status', '1')->where('platform', 'like', "%" . $search . "%")
            ->take($taker)->get();

        return view('retrieveHome', compact('modul'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<header>
    <div class="jumbotron jumbotron-fluid jumbotron-custom bg-dark text-white m-0 no-select position-relative">
        <div class="bg-icons">
        </div>
        <div class="container">
            <div class="row">
                <div class="col">
                    <h1 class="display-3 mb-0 text-white">Kamu lagi di beranda,</h1>
                    <p style="font-size: 1.2rem;">Tempat nongkrong dan belajar bareng!</p>
                </div>
            </div>
        </div>
    </div>
</header>
<article class="card-post my-5 no-select">
    <div class="container">
        <div id="ajax-holder" class="row">
            <input id="sum-data" type="hidden" value="{{ $sum_data }}">
            <input id="search-data" type="hidden" value="{{ $search }}">
            @foreach ($modul as $key)
            <div class="col-12 col-md-6 col-lg-4 mb-4 d-flex">
                <div class="card card-shadow rounded">
                    <a class="courses text-dark" href="{{ route('modul.show', $key->slug) }}">
                        <img class="card-img" src="{{ Storage::url($key->image) }}">
                        <div class="card-body">
                            <h4 class="card-title font-weight-bold mb-2">{{ $key->title }}</h4>
                           {{--  <div class="row">
                                <div class="col-6 mb-1">
                                    <span class="text-muted"><i class="fas fa-layer-group mr-2"></i>{{ $key->level }}</span>
                                </div>
                                <div class="col-6 mb-1">
                                    <span class="text-muted"><i class="fas fa-desktop mr-2"></i>{{ $key->platform }}</span>
                                </div>
                                <div class="col-6">
                                    <span class="text-muted"><i class="fas fa-bookmark mr-2"></i>{{ $key->lectures_count }} Materi</span>
                                </div>
                                <div class="col-6">
                                    <span class="text-muted"><i class="fas fa-user mr-2"></i>rubichandrap</span>
                                </div>
                            </div> --}}
                        </div>
                    </a>
                </div>
            </div>
            @endforeach
        </div>
        <hr class=mt-5>
        <div class="row">
            <div class="col-12 col-lg-12">
                <div class="text-center">
                    <a id="show-link" class="btn shadow-none text-primary" href="#">Show more</a>
                </div>
            </div>
        </div>
    </div>
</article>
@endsection

resources/views/kontak.blade.php
@extends('layouts.app')

@section('content')
<header>

</header>
<article class="card-post my-5 no-select">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-8 text-center">
                <div class="card border-0">
                    <div class="card-body">
                        <h3 class="text-muted">
                            Kirim saran dan temuan bug beserta screenshot ke rubichandrap@gmail.com
                        </h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>
@endsection

resources/views/retrieveHome.blade.php
@foreach ($modul as $key)
<div class="col-12 col-md-6 col-lg-4 mb-4 d-flex">
    <div class="card card-shadow rounded">
        <a class="courses text-dark" href="{{ route('modul.show', $key->slug) }}">
            <img class="card-img" src="{{ Storage::url($key->image) }}">
            <div class="card-body">
                <h4 class="card-title font-weight-bold mb-2">{{ $key->title }}</h4>
               {{--  <div class="row">
                    <div class="col-6 mb-1">
                        <span class="text-muted"><i class="fas fa-layer-group mr-2"></i>{{ $key->level }}</span>
                    </div>
                    <div class="col-6 mb-1">
                        <span class="text-muted"><i class="fas fa-desktop mr-2"></i>{{ $key->platform }}</span>
                    </div>
                    <div class="col-6">
                        <span class="text-muted"><i class="fas fa-bookmark mr-2"></i>{{ $key->lectures_count }} Materi</span>
                    </div>
                    <div class="col-6">
                        <span class="text-muted"><i class="fas fa-user mr-2"></i>rubichandrap</span>
                    </div>
                </div> --}}
            </div>
        </a>
    </div>
</div>
@endforeach

resources/views/tentang.blade.php
@extends('layouts.app')

@section('content')
<header>

</header>
<article class="card-post my-5 no-select">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-8 text-center">
                <div class="card border-0">
                    <div class="card-body">
                        <div>
                            <a class="btn bg-transparent shadow-none" href="#">
                                <img src="{{ asset('asset/main/images/rubi.jpg') }}" class="rounded-circle" width="160" height="160">
                            </a>
                        </div>
                        <div class="pt-2">
                            <div>
                                <h2 class="mb-0">
                                    Rubi Chandraputra
                                </h2>
                                <p class="text-muted">
                                    rubichandrap@gmail.com
                                </p>
                                <p class="text-muted mb-0">
                                    Portofolios:
                                </p>
                                <div>
                                    <a href="https://www.akpa.net.id">akpa.net.id</a>
                                    <span class="mx-2">|</span>
                                    <a href="http://www.omahngayomi.naufalibnusalam.com">omahngayomi</a>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div>
                            <p>
                                <span class="mr-2" style="font-size: 2rem;"><i class="fas fa-quote-left"></i></span><span class="font-weight-bold">eCourse</span>, merupakan sistem pembelajaran <i>online</i> atau yang
                                dikenal sebagai <i>E-Learning</i>, yang dibuat khusus bagi keluarga STMIK Muhammadiyah Jakarta.
                                Projek ini merupakan tugas akhir dan produk murni yang diciptakan untuk memenuhi syarat kelulusan jenjang
                                Strata-1 pada STMIK Muhammadiyah Jakarta.
                            </p>
                            <p>
                                <span class="font-weight-bold">eCourse</span> memiliki sistem yang layak untuk diimplementasikan
                                ke dalam suatu sistem pembelajaran <i>online</i> karena memiliki kompleksitas yang cukup tinggi. Projek ini
                                merupakan sebuah penyempurnaan dari beberapa projek saya sebelumnya, seperti website <i>Internet Service Provider</i>
                                <a href="https://www.akpa.net.id">AKPA</a> dan website yang merupakan produk dari lomba Jakbee 2019
                                <a href="http://www.omahngayomi.naufalibnusalam.com"> omahngayomi</a>, dan <span class="font-weight-bold">100% Made From Scratch</span>.
                            </p>
                            <p>
                                Saya mengucapkan <span class="font-weight-bold">Ribuan Terima Kasih</span> kepada orang-orang yang
                                telah mendukung saya dari segi mental dan ilmu. Terima Kasih kepada adik dan kedua orang tua, karena
                                tidak henti-hentinya memberikan semangat. Pujaan hati, Riska Alfiani <span class="text-red"><i class="fas fa-heart"></i>
                                </span> . Teman baik saya Naufal Ibnu Salam, ngoding bareng sama lo memang
                                momen cari ilmu paling luar biasa! <span class="font-weight-bold text-muted">jangan lupa projek vue js fal! </span>
                                <span class="text-green"><i class="fab fa-vuejs"></i></span> . Dan semua orang yang tidak bisa saya sebutkan satu persatu.
                            </p>
                            <p>
                                Do'a dan harapan saya, agar sistem <i>E-Learning</i> ini dapat diimplementasikan ke dalam sistem yang sudah berjalan
                                pada STMIK Muhammadiyah Jakarta. Bagi saya, tidak ada penghargaan dan apresiasi yang lebih baik dari pihak kampus kepada mahasiswa,
                                melainkan memberdayakan produk-produk ciptaan kami. Terima kasih para dosen. Semoga STMIK Muhammadiyah Jakarta dapat
                                terus berkembang detik demi detik. Aamiin! <span class="ml-2" style="font-size: 2rem;"><i class="fas fa-quote-right"></i></span>
                            </p>
                        </div>
                        <hr>
                        <div>
                            <span class="text-muted"><i>~ Rubi Chandraputra, 2020</i></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>
@endsection