routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function(){
    return view('welcome');
})->name('welcome');

Route::get('/tentang', 'TentangController@index')->name('tentang');

Route::get('/kontak', 'KontakController@index')->name('kontak');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/home/retrieve', 'HomeController@retrieve')->name('retrieve');

    /*password*/
    Route::name('password.')->group(function() {
        Route::get('/password/{id}/edit', 'PasswordController@edit')->name('edit');
        Route::patch('/password/{id}', 'PasswordController@update')->name('update');
    });

    /*profil*/
    Route::name('profile.')->group(function() {
        Route::get('/profile', 'ProfileController@index')->name('index');
        Route::patch('/profile/{id}', 'ProfileController@update')->name('update');
    });

    /*mahasiswa*/
    Route::name('mahasiswa.')->group(function() {
        Route::get('/mahasiswa', 'MahasiswaController@index')->name('index');
        Route::get('/mahasiswa/create', 'MahasiswaController@create')->name('create');
        Route::post('/mahasiswa', 'MahasiswaController@store')->name('store');
        Route::get('/mahasiswa/{id}', 'MahasiswaController@show')->name('show');
        Route::get('/mahasiswa/{id}/edit', 'MahasiswaController@edit')->name('edit');
        Route::patch('/mahasiswa/{id}', 'MahasiswaController@update')->name('update');
        Route::delete('/mahasiswa/{id}', 'MahasiswaController@destroy')->name('destroy');  
    });

    /*dosen*/
    Route::name('dosen.')->group(function() {
        Route::get('/dosen', 'DosenController@index')->name('index');
        Route::get('/dosen/create', 'DosenController@create')->name('create');
        Route::post('/dosen', 'DosenController@store')->name('store');
        Route::get('/dosen/{id}', 'DosenController@show')->name('show');
        Route::get('/dosen/{id}/edit', 'DosenController@edit')->name('edit');
        Route::patch('/dosen/{id}', 'DosenController@update')->name('update');
        Route::delete('/dosen/{id}', 'DosenController@destroy')->name('destroy');
    });

    /*kelas*/
    Route::name('kelas.')->group(function() {
        Route::get('/kelas', 'KelasController@index')->name('index');
        Route::get('/kelas/list', 'KelasController@kelas_list')->name('list');
        Route::get('/kelas/list/ajax', 'KelasController@ajax_kelas_list')->name('ajax_list');
        Route::get('/kelas/join', 'KelasController@kelas_join')->name('join');
        Route::get('/kelas/join/ajax', 'KelasController@ajax_kelas_join')->name('ajax_join');
        Route::post('/kelas/join', 'KelasController@token_handler')->name('token_handler');
        Route::get('/kelas/{id}/desc', 'KelasController@desc')->name('desc');
        Route::get('/kelas/{id}/desc/ajax', 'KelasController@ajax_desc')->name('ajax_desc');
        Route::get('/kelas/{id}/peserta', 'KelasController@peserta')->name('peserta');
        Route::get('/kelas/{id}/peserta/ajax', 'KelasController@ajax_peserta')->name('ajax_peserta');
        Route::patch('/kelas/{kelas_id}/peserta/{user_id}', 'KelasController@kick_peserta')->name('kick_peserta');
        Route::get('/kelas/create', 'KelasController@create')->name('create');
        Route::post('/kelas', 'KelasController@store')->name('store');
        Route::get('/kelas/{id}', 'KelasController@show')->name('show');
        Route::get('/kelas/{id}/edit', 'KelasController@edit')->name('edit');
        Route::patch('/kelas/{id}', 'KelasController@update')->name('update');
        Route::delete('/kelas/{id}', 'KelasController@destroy')->name('destroy');
        Route::post('/kelas/status', 'KelasController@status')->name('status');
    });

    Route::name('session.')->group(function() {
        Route::get('/kelas/{id}/session', 'SessionController@index')->name('index');
        Route::get('/kelas/{id}/session/ajax', 'SessionController@ajax_session')->name('ajax_session');
        Route::get('/kelas/{id}/session/create', 'SessionController@create')->name('create');
        Route::post('/kelas/{id}/session', 'SessionController@store')->name('store');
        Route::get('/kelas/{id}/session/{session_of}', 'SessionController@show')->name('show');
        Route::get('/kelas/{id}/session/{session_of}/edit', 'SessionController@edit')->name('edit');
        Route::patch('/kelas/{id}/session/{session_of}', 'SessionController@update')->name('update');
        Route::delete('/kelas/{id}/session/{session_of}', 'SessionController@destroy')->name('destroy');
        Route::post('/kelas/session/status', 'SessionController@status')->name('status');
    });

    Route::name('posting.')->group(function() {
        Route::post('/kelas/{id}/session/{session_of}/posting', 'PostingController@store')->name('store');
        Route::delete('/kelas/session/posting/{id}', 'PostingController@destroy')->name('destroy');
    });
    
    Route::name('comment.')->group(function() {
        Route::post('/kelas/session/posting/{posting_id}/comment', 'CommentController@store')->name('store');
        Route::delete('/kelas/session/posting/comment/{comment_id}', 'CommentController@destroy')->name('destroy');
    });

    Route::name('tugas_comment.')->group(function() {
        Route::post('/kelas/session/tugas/{tugas_id}/comment', 'TugasCommentController@store')->name('store');
        Route::delete('/kelas/session/tugas/comment/{comment_id}', 'TugasCommentController@destroy')->name('destroy');
    });

    Route::name('absent.')->group(function() {
        Route::get('/kelas/{kelas_id}/session/{session_of}/absent', 'AbsentController@index')->name('index');
        Route::post('/kelas/{kelas_id}/session/{session_of}/absent', 'AbsentController@store')->name('store');
    });

    Route::name('tugas.')->group(function() {
        Route::get('/kelas/{kelas_id}/session/{session_of}/tugas', 'TugasController@index')->name('index');
        Route::post('/kelas/{kelas_id}/session/{session_of}/tugas', 'TugasController@store')->name('store');
        Route::delete('/kelas/session/tugas/{id}', 'TugasController@destroy')->name('destroy');
    });

    /*modul*/
    Route::name('modul.')->group(function() {
        Route::get('/modul', 'ModulController@index')->name('index');
        Route::get('/modul/{slug}/desc', 'ModulController@desc')->name('desc');
        Route::get('/modul/{slug}/desc/ajax', 'ModulController@ajax_desc')->name('ajax_desc');
        Route::get('/modul/create', 'ModulController@create')->name('create');
        Route::post('/modul', 'ModulController@store')->name('store');
        Route::get('/modul/{slug}', 'ModulController@show')->name('show');
        Route::get('/modul/{slug}/edit', 'ModulController@edit')->name('edit');
        Route::patch('/modul/{id}', 'ModulController@update')->name('update');
        Route::delete('/modul/{id}', 'ModulController@destroy')->name('destroy');
        Route::post('/modul/status', 'ModulController@status')->name('status');
    });

    /*lecture*/
    Route::name('lecture.')->group(function() {
        Route::get('/modul/{slug}/lecture', 'LectureController@index')->name('index');
        Route::get('/modul/{slug}/lecture/ajax', 'LectureController@ajax_lecture')->name('ajax_lecture');
        Route::get('/modul/{slug}/lecture/create', 'LectureController@create')->name('create');
        Route::post('/modul/{slug}/lecture', 'LectureController@store')->name('store');
        Route::get('/modul/{slug}/lecture/{urutan}', 'LectureController@show')->name('show');
        Route::get('/modul/{slug}/lecture/{urutan}/edit', 'LectureController@edit')->name('edit');
        Route::patch('/modul/{slug}/lecture/{urutan}', 'LectureController@update')->name('update');
        Route::delete('/modul/{slug}/lecture/{urutan}', 'LectureController@destroy')->name('destroy');
        Route::post('/modul/lecture/status', 'LectureController@status')->name('status');
    });

    /*pencarian*/
    Route::get('/pencarian', 'PencarianController@index')->name('pencarian');
});

Route::get('/clear-cache', function () {
    $exitCode =
        Artisan::call('config:clear');
    $exitCode =
        Artisan::call('cache:clear');
    $exitCode =
        Artisan::call('config:cache');
    return 'Cache cleared!';
});

resources/views/template/footer.blade.php
<footer class="mt-4">
    <div class="bg-secondary">
        <div class="container">
            <div class="card-body">
                <div class="row align-items-center justify-content-center">
                    <div class="col-12 col-lg-3 px-md-0 mb-2 mb-lg-0 text-center text-lg-left">
                        <a style="font-family: 'Nunito-ExtraBold';" class="navbar-brand mr-auto no-select text-muted disabled footer-brand">
                            <i class="fas fa-graduation-cap"></i>eCOURSE
                        </a>
                    </div>
                    <div class="col-12 col-lg-9">
                        <div class="row">
                            <div class="col-12 col-lg-4 mb-2 mb-lg-0 text-center text-lg-left">
                                <h4 class="text-muted">Contact</h4>
                                <span class="text-muted">rubichandrap@gmail.com</span>
                            </div>
                            <div class="col-12 col-lg-4 mb-2 mb-lg-0 text-center text-lg-left">
                                <h4 class="text-muted">Made For</h4>
                                <span class="text-muted">Own Purposes</span>
                            </div>
                            <div class="col-12 col-lg-4 mb-2 mb-lg-0 text-center text-lg-left">
                                <h4 class="text-muted">License</h4>
                                <span class="text-muted">MIT License &copy; 2020 Rubi Chandraputra</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/template/gotop.blade.php
    <div class="go-top btn-default">
        <span><i class="fa fa-arrow-up"></i></span>
        <span>BACK</span>
        <span>TO</span>
        <span>TOP</span>
    </div>

resources/views/template/head.blade.php
    <!-- META -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="author" content="Rubi Chandraputra">

    <!-- CSS -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <!-- css argon -->
    <link rel="stylesheet" href="{{ asset('asset/argon/css/argon-dashboard.min.css') }}">
    <!-- css style -->
    <link rel="stylesheet" href="{{ asset('asset/main/css/style.css') }}">
    <!-- css nucleo -->
    <link rel="stylesheet" href="{{ asset('asset/argon/js/plugins/nucleo/css/nucleo.css') }}">
    <!-- css cololib -->
    <link href="{{ asset('asset/colorlib/css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('asset/colorlib/fonts/css/material-design-iconic-font.css') }}" rel="stylesheet">
    <!-- css fontawesome -->
    <link rel="stylesheet" href="{{ asset('asset/fontawesome-free-5.12.0/css/all.min.css') }}">
    <!-- css bootstrap datatables -->
    <link rel="stylesheet" href="{{ asset('asset/main/css/dataTables.bootstrap.min.css') }}">
    <!-- css bootstrap responsive -->
    <link rel="stylesheet" href="{{ asset('asset/main/css/responsive.bootstrap.min.css') }}">

    <!-- ICON -->
    <link href="{{ asset('asset/main/images/icon.png') }}" rel="icon" type="image/x-ico">

    <!-- PROJEK INI MERUPAKAN TUGAS AKHIR SEBAGAI SYARAT KELULUSAN JENJANG STRATA-1 PADA STMIK MUHAMMADIYAH JAKARTA -->
    <!-- DESAIN PROJEK INI TERINSPIRASI DARI WWW.DICODING.COM, BACK-END MERUPAKAN IMPLEMENTASI DAN PENYEMPURNAAN 
    DARI RISET DAN PROJEK-PROJEK SAYA SEBELUMNYA ANTARA LAIN WWW.AKPA.NET.ID DAN WWW.OMAHNGAYOMI.NAUFALIBNUSALAM.COM -->

    <!-- RUBI CHANDRAPUTRA, 2020 -->

resources/views/template/horizontalMenu.blade.php
<ul class="nav">
    <li class="nav-item">
        <a class="nav-link {{ (request()->is('home')) ? 'active' : '' }}" href="{{ url('/home')}}">Beranda</a>
    </li>
    @auth
    <li class="nav-item">
        <div class="dropdown">
            @if(Auth::user()->hasRole('admin') || Auth::user()->hasRole('dosen'))
            <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownActivities" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Activities
            </a>
            @else
            <a class="nav-link {{ (request()->is('kelas')) ? 'active' : '' }}" href="{{ url('/kelas') }}">
                Kelas
            </a>
            @endif
            @if(Auth::user()->hasRole('admin'))
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow" aria-labelledby="dropdownActivities">
                <a class="dropdown-item {{ (request()->is('mahasiswa')) ? 'active' : '' }}" href="{{ url('/mahasiswa')}}">Mahasiswa</a>
                <a class="dropdown-item {{ (request()->is('dosen')) ? 'active' : '' }}" href="{{ url('/dosen')}}">Dosen</a>
                <a class="dropdown-item {{ (request()->is('kelas')) ? 'active' : '' }}" href="{{ url('/kelas')}}">Kelas</a>
                <a class="dropdown-item {{ (request()->is('modul')) ? 'active' : '' }}" href="{{ url('/modul')}}">Modul</a>
            </div>
            @elseif(Auth::user()->hasRole('dosen'))
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow" aria-labelledby="dropdownActivities">
                <a class="dropdown-item {{ (request()->is('kelas')) ? 'active' : '' }}" href="{{ url('/kelas')}}">Kelas</a>
                <a class="dropdown-item {{ (request()->is('modul')) ? 'active' : '' }}" href="{{ url('/modul')}}">Modul</a>
            </div>
            @endif
        </div>
    </li>
    @endauth
    <li class="nav-item">
        <a class="nav-link" href="https://www.stmikmj.ac.id/" target="_blank">Kampus</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {{ (request()->is('tentang')) ? 'active' : '' }}" href="{{ url('/tentang')}}">Tentang</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {{ (request()->is('kontak')) ? 'active' : '' }}" href="{{ url('/kontak') }}">Kontak</a>
    </li>
</ul>

resources/views/template/menubar.blade.php
    <div class="menu-icon {{ (! request()->is('/')) ? 'icon-b' : ''}}">
        <span></span>
        <span></span>
        <span></span>
    </div>

resources/views/template/mobileMenu.blade.php
@include('template.sidebar')
@include('template.menubar')

resources/views/template/profileMenu.blade.php
<ul class="nav">
    <li class="nav-item">
        <a class="nav-link" href="#" id="dropdownProfile" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="rounded-circle" src="{{ Storage::url(Auth::user()->profile->image) }}" alt="profile-iamge" width="35" height="35">
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow" aria-labelledby="dropdownProfile">
            <a class="dropdown-item {{ (request()->is('profile')) ? 'active' : '' }}" href="{{url('/profile')}}">Profile</a>
            <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                    document.getElementById('logout-form-profile').submit();">
                {{ __('Logout') }}
            </a>
        </div>
        <form id="logout-form-profile" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
    </li>
</ul>

resources/views/template/script.blade.php
<!-- JS -->
<script src="{{ asset('js/app.js') }}"></script>
<!-- js jquery -->
{{-- <script src="{{ asset('asset/argon/js/plugins/jquery/dist/jquery.min.js') }}"></script> --}}
<script src="{{ asset('asset/jquery/jquery-3.4.1.min.js') }}"></script>
<!-- js argon -->
<script src="{{ asset('asset/argon/js/argon-dashboard.min.js') }}"></script>
<!-- js main -->
<script src="{{ asset('asset/main/js/animate.js') }}"></script>
<!-- js ajax calls -->
<script src="{{ asset('asset/main/js/ajax-calls.js') }}"></script>
<!-- js fontawesome -->
<script src="{{ asset('asset/fontawesome-free-5.12.0/js/all.min.js') }}"></script>
<!-- js jquery datatables -->
<script src="{{ asset('asset/main/js/jquery.dataTables.min.js') }}"></script>
<!-- js bootstrap datatables -->
<script src="{{ asset('asset/main/js/dataTables.bootstrap4.min.js') }}"></script>
<!-- datatables activation -->
<script type="text/javascript">
    $(document).ready(function() {
        const table = $('#table');
        const deflect = $('#table #deflection');
        if (table) {
            if (deflect.length < 1) {
                $(table).DataTable({
                    scrollX: true,
                    scrollCollapse: true,
                });
            } else {
                return false;
            }
        }
    });
</script>
<!-- ck finder -->
<script src="{{ asset('asset/ckfinder_php_3.5.1/ckfinder/ckfinder.js') }}"></script>
<!-- ck editor -->
<script src="{{ asset('asset/ckeditor_4.14.0_standard/ckeditor/ckeditor.js') }}"></script>
<!-- ck editor activation -->
<script type="text/javascript">
    $(document).ready(() => {
        const base_url = window.location.origin;
        const ckEditor = document.querySelector('#editor');
        if (ckEditor) {
            CKFinder.setupCKEditor();
            CKEDITOR.replace( 'editor' );
        }
    });
</script>

resources/views/template/showKelasHeader.blade.php
<header>
    <div class="container-fluid p-0 bg-gray-dark">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb m-0 bg-transparent">
                    @if(Auth::user()->hasRole('admin') || Auth::user()->hasRole('dosen'))
                    <li class="breadcrumb-item"><a class="text-white" href="{{ route('kelas.index') }}">Kelas</a></li>
                    @else
                    <!-- different view from what admin and dosen get -->
                    <li class="breadcrumb-item"><a class="text-white" href="{{ route('kelas.index') }}">Kelas</a></li>
                    @endif
                    <li class="breadcrumb-item active" aria-current="page">{{ $kelas->title }}</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="jumbotron jumbotron-fluid jumbotron-custom bg-dark text-white m-0 no-select position-relative">
        <div class="bg-icons">
        </div>
    </div>
    <div class="jumbotron-content mt--9">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card bg-transparent border-0">
                        <div class="row">
                            <div class="col-12 col-md-8 col-lg-6">
                                <h1 class="text-white font-weight-bold mb-1">{{ $kelas->title }}</h1>
                                <div class="row">
                                    <div class="col-6">
                                        <span class="text-white">Dosen : {{ $kelas->user->name }}</span>
                                    </div>
                                    <div class="col-6">
                                        <span class="text-white">Sesi : {{ count($session) }} dari {{ $kelas->sessions }} Pertemuan</span>
                                    </div>
                                    <div class="col-6">
                                        <span class="text-white">Partisipan : {{ $kelas->user_joined_count }} Peserta</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

resources/views/template/showModulHeader.blade.php
<header>
    <div class="container-fluid p-0 bg-gray-dark">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb m-0 bg-transparent">
                    <li class="breadcrumb-item"><a class="text-white" href="{{ route('home') }}">Beranda</a></li>
                    @if(Auth::user()->hasRole('admin') || Auth::user()->hasRole('dosen'))
                    <li class="breadcrumb-item"><a class="text-white" href="{{ route('modul.index') }}">Modul</a></li>
                    @endif
                    <li class="breadcrumb-item active" aria-current="page">{{ $modul->title }}</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="jumbotron jumbotron-fluid jumbotron-custom bg-dark text-white m-0 no-select position-relative">
        <div class="bg-icons">
        </div>
    </div>
    <div class="jumbotron-content mt--9">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-9">
                    <div class="card bg-transparent border-0">
                        <div class="row">
                            <div class="col-md-6 col-lg-5 mb-3 mb-md-0">
                                <img class="card-img" src="{{ Storage::url($modul->image) }}">
                                @if(Auth::user()->hasRole('admin') || Auth::user()->hasRole('dosen'))
                                <div class="position-absolute top-0 left-3">
                                    <ul class="pt-2">
                                        <li class="p-0">
                                            <a class="btn btn-sm btn-primary" href="javascript:history.back()" title="Back">
                                                <i class="fas fa-backspace"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="position-absolute top-0 right-3">
                                    <ul class="pt-2">
                                        <li class="p-0">
                                            <form action="{{ route('modul.status') }}" method="POST" enctype="multipart/form-data">
                                                @csrf
                                                <input class="mb-1" type="hidden" name="id" value="{{ $modul->id }}">
                                                <input type="hidden" name="status" value="1">
                                                <button type="submit" class="btn btn-sm btn-default" {{ $modul->status == '1' ? 'disabled' : '' }}><i class="fa fa-check" aria-hidden="true" title="Publish"></i></button>
                                            </form>
                                        </li>
                                        <li class="p-0">
                                            <form action="{{ route('modul.status') }}" method="POST" enctype="multipart/form-data">
                                                @csrf
                                                <input type="hidden" name="id" value="{{ $modul->id }}">
                                                <input type="hidden" name="status" value="0">
                                                <button type="submit" class="btn btn-sm btn-default" {{ $modul->status == '0' ? 'disabled' : '' }}><i class="fa fa-eye-slash" aria-hidden="true" title="Hidden"></i></button>
                                            </form>
                                        </li>
                                        <li class="p-0">
                                            <a class="btn btn-sm btn-success" href="{{route('modul.edit', $modul->slug)}}" title="Edit">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                @endif
                            </div>
                            <div class="col-md-6 col-lg-7">
                                <h1 class="text-white-custom font-weight-bold mb-1">{{ $modul->title }}</h1>
                                <div class="row">
                                    <div class="col-6">
                                        <span class="text-white-custom">Level : {{ $modul->level }}</span>
                                    </div>
                                    <div class="col-6">
                                        <span class="text-white-custom">Platform : {{ $modul->platform }}</span>
                                    </div>
                                    <div class="col-6">
                                        <span class="text-white-custom">Materi : {{ $lecture }}</span>
                                    </div>
                                    <div class="col-6">
                                        <span class="text-white-custom">Penyusun : rubichandrap</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

resources/views/template/showSessionElipsisMenu.blade.php
<a class="d-lg-none post-action-icon" href="#" role="button" id="dropdownFeatures" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-h"></i>
    </a>
    <div class="d-lg-none dropdown-menu dropdown-menu-right dropdown-menu-arrow" aria-labelledby="dropdownFeatures">
        <a class="dropdown-item {{ request()->is('kelas/'.$kelas->id.'/session/'.$session->session_of) ? 'active' : '' }}" href="{{ route('session.show', [$kelas->id, $session->session_of]) }}">
            Overview
        </a>
        <a class="dropdown-item {{ request()->is('kelas/'.$kelas->id.'/session/'.$session->session_of.'/absent') ? 'active' : '' }}" href="{{route('absent.index', [$kelas->id, $session->session_of])}}">Absen</a>
        <a class="dropdown-item {{ (request()->is('modul')) ? 'active' : '' }}" href="{{ url('/modul')}}">Tugas</a>

        @if($all_session->count() > 1)
        <div class="dropdown-divider"></div>
        @endif

        <div class="row">
            @if($session->session_of < 2 && $all_session->count() > 1)
                <div class="col-12">
                    <a class="dropdown-item" href="{{ route('session.show', [$kelas->id, intval($session->session_of + 1)]) }}">Sesi selanjutnya</a>
                </div>
                @elseif($session->session_of == $all_session->count() && $all_session->count() > 1)
                <div class="col-12">
                    <a class="dropdown-item" href="{{ route('session.show', [$kelas->id, intval($session->session_of - 1)]) }}">Sesi sebelumnya</a>
                </div>
                @elseif($session->session_of > 1 && $session->session_of < $all_session->count())
                    <div class="col-12">
                        <a class="dropdown-item" href="{{ route('session.show', [$kelas->id, intval($session->session_of - 1)]) }}">Sesi sebelumnya</a>
                    </div>
                    <div class="col-12">
                        <a class="dropdown-item" href="{{ route('session.show', [$kelas->id, intval($session->session_of + 1)]) }}">Sesi selanjutnya</a>
                    </div>
                    @endif
        </div>
    </div>