routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function(){
    return view('welcome');
})->name('welcome');

Route::get('/tentang', 'TentangController@index')->name('tentang');

Route::get('/kontak', 'KontakController@index')->name('kontak');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/home/retrieve', 'HomeController@retrieve')->name('retrieve');

    /*password*/
    Route::name('password.')->group(function() {
        Route::get('/password/{id}/edit', 'PasswordController@edit')->name('edit');
        Route::patch('/password/{id}', 'PasswordController@update')->name('update');
    });

    /*profil*/
    Route::name('profile.')->group(function() {
        Route::get('/profile', 'ProfileController@index')->name('index');
        Route::patch('/profile/{id}', 'ProfileController@update')->name('update');
    });

    /*mahasiswa*/
    Route::name('mahasiswa.')->group(function() {
        Route::get('/mahasiswa', 'MahasiswaController@index')->name('index');
        Route::get('/mahasiswa/create', 'MahasiswaController@create')->name('create');
        Route::post('/mahasiswa', 'MahasiswaController@store')->name('store');
        Route::get('/mahasiswa/{id}', 'MahasiswaController@show')->name('show');
        Route::get('/mahasiswa/{id}/edit', 'MahasiswaController@edit')->name('edit');
        Route::patch('/mahasiswa/{id}', 'MahasiswaController@update')->name('update');
        Route::delete('/mahasiswa/{id}', 'MahasiswaController@destroy')->name('destroy');  
    });

    /*dosen*/
    Route::name('dosen.')->group(function() {
        Route::get('/dosen', 'DosenController@index')->name('index');
        Route::get('/dosen/create', 'DosenController@create')->name('create');
        Route::post('/dosen', 'DosenController@store')->name('store');
        Route::get('/dosen/{id}', 'DosenController@show')->name('show');
        Route::get('/dosen/{id}/edit', 'DosenController@edit')->name('edit');
        Route::patch('/dosen/{id}', 'DosenController@update')->name('update');
        Route::delete('/dosen/{id}', 'DosenController@destroy')->name('destroy');
    });

    /*kelas*/
    Route::name('kelas.')->group(function() {
        Route::get('/kelas', 'KelasController@index')->name('index');
        Route::get('/kelas/list', 'KelasController@kelas_list')->name('list');
        Route::get('/kelas/list/ajax', 'KelasController@ajax_kelas_list')->name('ajax_list');
        Route::get('/kelas/join', 'KelasController@kelas_join')->name('join');
        Route::get('/kelas/join/ajax', 'KelasController@ajax_kelas_join')->name('ajax_join');
        Route::post('/kelas/join', 'KelasController@token_handler')->name('token_handler');
        Route::get('/kelas/{id}/desc', 'KelasController@desc')->name('desc');
        Route::get('/kelas/{id}/desc/ajax', 'KelasController@ajax_desc')->name('ajax_desc');
        Route::get('/kelas/{id}/peserta', 'KelasController@peserta')->name('peserta');
        Route::get('/kelas/{id}/peserta/ajax', 'KelasController@ajax_peserta')->name('ajax_peserta');
        Route::patch('/kelas/{kelas_id}/peserta/{user_id}', 'KelasController@kick_peserta')->name('kick_peserta');
        Route::get('/kelas/create', 'KelasController@create')->name('create');
        Route::post('/kelas', 'KelasController@store')->name('store');
        Route::get('/kelas/{id}', 'KelasController@show')->name('show');
        Route::get('/kelas/{id}/edit', 'KelasController@edit')->name('edit');
        Route::patch('/kelas/{id}', 'KelasController@update')->name('update');
        Route::delete('/kelas/{id}', 'KelasController@destroy')->name('destroy');
        Route::post('/kelas/status', 'KelasController@status')->name('status');
    });

    Route::name('session.')->group(function() {
        Route::get('/kelas/{id}/session', 'SessionController@index')->name('index');
        Route::get('/kelas/{id}/session/ajax', 'SessionController@ajax_session')->name('ajax_session');
        Route::get('/kelas/{id}/session/create', 'SessionController@create')->name('create');
        Route::post('/kelas/{id}/session', 'SessionController@store')->name('store');
        Route::get('/kelas/{id}/session/{session_of}', 'SessionController@show')->name('show');
        Route::get('/kelas/{id}/session/{session_of}/edit', 'SessionController@edit')->name('edit');
        Route::patch('/kelas/{id}/session/{session_of}', 'SessionController@update')->name('update');
        Route::delete('/kelas/{id}/session/{session_of}', 'SessionController@destroy')->name('destroy');
        Route::post('/kelas/session/status', 'SessionController@status')->name('status');
    });

    Route::name('posting.')->group(function() {
        Route::post('/kelas/{id}/session/{session_of}/posting', 'PostingController@store')->name('store');
        Route::delete('/kelas/session/posting/{id}', 'PostingController@destroy')->name('destroy');
    });
    
    Route::name('comment.')->group(function() {
        Route::post('/kelas/session/posting/{posting_id}/comment', 'CommentController@store')->name('store');
        Route::delete('/kelas/session/posting/comment/{comment_id}', 'CommentController@destroy')->name('destroy');
    });

    Route::name('tugas_comment.')->group(function() {
        Route::post('/kelas/session/tugas/{tugas_id}/comment', 'TugasCommentController@store')->name('store');
        Route::delete('/kelas/session/tugas/comment/{comment_id}', 'TugasCommentController@destroy')->name('destroy');
    });

    Route::name('absent.')->group(function() {
        Route::get('/kelas/{kelas_id}/session/{session_of}/absent', 'AbsentController@index')->name('index');
        Route::post('/kelas/{kelas_id}/session/{session_of}/absent', 'AbsentController@store')->name('store');
    });

    Route::name('tugas.')->group(function() {
        Route::get('/kelas/{kelas_id}/session/{session_of}/tugas', 'TugasController@index')->name('index');
        Route::post('/kelas/{kelas_id}/session/{session_of}/tugas', 'TugasController@store')->name('store');
        Route::delete('/kelas/session/tugas/{id}', 'TugasController@destroy')->name('destroy');
    });

    /*modul*/
    Route::name('modul.')->group(function() {
        Route::get('/modul', 'ModulController@index')->name('index');
        Route::get('/modul/{slug}/desc', 'ModulController@desc')->name('desc');
        Route::get('/modul/{slug}/desc/ajax', 'ModulController@ajax_desc')->name('ajax_desc');
        Route::get('/modul/create', 'ModulController@create')->name('create');
        Route::post('/modul', 'ModulController@store')->name('store');
        Route::get('/modul/{slug}', 'ModulController@show')->name('show');
        Route::get('/modul/{slug}/edit', 'ModulController@edit')->name('edit');
        Route::patch('/modul/{id}', 'ModulController@update')->name('update');
        Route::delete('/modul/{id}', 'ModulController@destroy')->name('destroy');
        Route::post('/modul/status', 'ModulController@status')->name('status');
    });

    /*lecture*/
    Route::name('lecture.')->group(function() {
        Route::get('/modul/{slug}/lecture', 'LectureController@index')->name('index');
        Route::get('/modul/{slug}/lecture/ajax', 'LectureController@ajax_lecture')->name('ajax_lecture');
        Route::get('/modul/{slug}/lecture/create', 'LectureController@create')->name('create');
        Route::post('/modul/{slug}/lecture', 'LectureController@store')->name('store');
        Route::get('/modul/{slug}/lecture/{urutan}', 'LectureController@show')->name('show');
        Route::get('/modul/{slug}/lecture/{urutan}/edit', 'LectureController@edit')->name('edit');
        Route::patch('/modul/{slug}/lecture/{urutan}', 'LectureController@update')->name('update');
        Route::delete('/modul/{slug}/lecture/{urutan}', 'LectureController@destroy')->name('destroy');
        Route::post('/modul/lecture/status', 'LectureController@status')->name('status');
    });

    /*pencarian*/
    Route::get('/pencarian', 'PencarianController@index')->name('pencarian');
});

Route::get('/clear-cache', function () {
    $exitCode =
        Artisan::call('config:clear');
    $exitCode =
        Artisan::call('cache:clear');
    $exitCode =
        Artisan::call('config:cache');
    return 'Cache cleared!';
});

resources/views/func/ajaxKelasList.blade.php
<div class="row">
    <div class="col-12">
        <h2>Daftar Kelas</h2>
        <div class="form-inline my-4">
            <div id="search-form" class="js-live-search form-inline mb-0 mr-2 w-100">
                <input class="form-control mr-2 w-75" type="text" placeholder="Cari Kelas" name="search_input_materi" value="" />
                <div class="p-2">
                    <i class="fas fa-search"></i>
                </div>
            </div>
        </div>
        <div class="card border-0">
            <table class="table table-responsive-sm table-hover js-live-search-table">
                <thead>
                    <tr>
                        <th scope="col" style="font-size: .8rem !important;">Title</th>
                        <th scope="col" style="font-size: .8rem !important;">Dosen</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($kelas as $key)
                    <tr>
                        <th scope="row" style="font-size: 1rem !important;">
                            <a href="{{ route('kelas.show', $key->id) }}">
                                {{ $key->title }}
                            </a>
                        </th>
                        <td scope="row" style="font-size: 1rem !important;">
                            {{ $key->user->name }}<i class="fa fa-star ml-2 text-yellow"></i>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

resources/views/func/ajaxModulMateri.blade.php
<div class="row">
    <div class="col-12">
        <h2>Daftar Materi</h2>
        <div class="form-inline my-4">
            <div id="search-form" class="js-live-search form-inline mb-0 mr-2 w-100">
                <input class="form-control mr-2 w-75" type="text" placeholder="Cari Materi" name="search_input_materi" value="" />
                <div class="p-2">
                    <i class="fas fa-search"></i>
                </div>
            </div>
        </div>
        <div class="card border-0">
            <table class="table table-responsive-sm table-hover js-live-search-table">
                <thead>
                    <tr>
                        <th scope="col" style="font-size: .8rem !important;">Materi</th>
                        <th scope="col" style="font-size: .8rem !important;">Status</th>
                        @if(Auth::user()->hasRole('admin') || Auth::user()->hasRole('dosen'))
                        <th scope="col" style="font-size: .8rem !important;">Publish</th>
                        <th scope="col" style="font-size: .8rem !important;">Actions</th>
                        @endif
                    </tr>
                </thead>
                <tbody>
                    @foreach($list as $key)
                    <tr>
                        <th scope="row" style="font-size: 1rem !important;">
                            <a href="{{ route('lecture.show', [$modul->slug, $key->urutan]) }}">
                                {{ $key->title }}
                            </a>
                        </th>
                        <td scope="row" style="font-size: 1rem !important;">
                            @if (isset($learn_status[$key->id]) && $learn_status[$key->id] == Auth::user()->id)
                            <i class="fas fa-check mr-2"></i>Selesai
                            @endif
                        </td>
                        @if(Auth::user()->hasRole('admin') || Auth::user()->hasRole('dosen'))
                        <td scope="row">
                            <ul>
                                <li>
                                    <form action="{{ route('lecture.status') }}" method="POST" enctype="multipart/form-data">
                                        @csrf
                                        <input type="hidden" name="id" value="{{ $key->id }}">
                                        <input type="hidden" name="status" value="1">
                                        <button type="submit" class="btn btn-sm btn-default" {{ $key->status == '1' ? 'disabled' : '' }}><i class="fa fa-check" aria-hidden="true"></i></button>
                                    </form>
                                </li>
                                <li>
                                    <form action="{{ route('lecture.status') }}" method="POST" enctype="multipart/form-data">
                                        @csrf
                                        <input type="hidden" name="id" value="{{ $key->id }}">
                                        <input type="hidden" name="status" value="0">
                                        <button type="submit" class="btn btn-sm btn-default" {{ $key->status == '0' ? 'disabled' : '' }}><i class="fa fa-eye-slash" aria-hidden="true"></i></button>
                                    </form>
                                </li>
                            </ul>
                        </td>
                        <td scope="row">
                            <ul>
                                <li class="p-0">
                                    <a class="btn btn-sm btn-info" href="{{ route('lecture.show', [$modul->slug, $key->urutan]) }}">Show</a>
                                </li>
                                <li class="p-0">
                                    <a class="btn btn-sm btn-success" href="{{route('lecture.edit', [$modul->slug, $key->urutan])}}">Edit</a>
                                </li>
                                <li class="p-0">
                                    <form method="POST" action="{{route('lecture.destroy', [$modul->slug, $key->urutan])}}">
                                        @csrf
                                        <input type="hidden" name="_method" value="DELETE" />
                                        <button class="btn btn-sm btn-danger del-btn" type="button" data-toggle="modal" data-target="#modal-del{{$key->urutan}}">Delete</button>
                                        <div id="modal-del{{$key->urutan}}" class="modal fade" tabindex="-1" role="dialog">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title">Hapus Data</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p class="text-wrap">Anda yakin ingin menghapus Materi pada {{ $modul->slug }} dengan urut : {{$key->urutan}} ?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="submit" class="btn btn-primary">Ya</button>
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </li>
                            </ul>
                        </td>
                        @endif
                    </tr>
                    @endforeach
                    @if(Auth::user()->hasRole('admin') || Auth::user()->hasRole('dosen'))
                    @foreach($unpublish as $key)
                    <tr>
                        <th scope="row" style="font-size: 1rem !important;"><a class="text-muted" href="{{ route('lecture.edit', [$modul->slug, $key->urutan]) }}">{{ $key->title }}</a></th>
                        <td scope="row" style="font-size: 1rem !important;">
                            @if (isset($learn_status[$key->id]) && $learn_status[$key->id] == Auth::user()->id)
                            <i class="fas fa-check mr-2"></i>Selesai
                            @endif
                        </td>
                        <td scope="row">
                            <ul>
                                <li>
                                    <form action="{{ route('lecture.status', $modul->slug) }}" method="POST" enctype="multipart/form-data">
                                        @csrf
                                        <input class="mb-1" type="hidden" name="id" value="{{ $key->id }}">
                                        <input type="hidden" name="status" value="1">
                                        <button type="submit" class="btn btn-sm btn-default" {{ $key->status == '1' ? 'disabled' : '' }}><i class="fa fa-check" aria-hidden="true"></i></button>
                                    </form>
                                </li>
                                <li>
                                    <form action="{{ route('lecture.status', $modul->slug) }}" method="POST" enctype="multipart/form-data">
                                        @csrf
                                        <input type="hidden" name="id" value="{{ $key->id }}">
                                        <input type="hidden" name="status" value="0">
                                        <button type="submit" class="btn btn-sm btn-default" {{ $key->status == '0' ? 'disabled' : '' }}><i class="fa fa-eye-slash" aria-hidden="true"></i></button>
                                    </form>
                                </li>
                            </ul>
                        </td>
                        <td scope="row">
                            <ul>
                                <li class="p-0">
                                    <a class="btn btn-sm btn-info" href="{{ route('lecture.edit', [$modul->slug, $key->urutan]) }}">Show</a>
                                </li>
                                <li class="p-0">
                                    <a class="btn btn-sm btn-success" href="{{route('lecture.edit', [$modul->slug, $key->urutan])}}">Edit</a>
                                </li>
                                <li class="p-0">
                                    <form method="POST" action="{{route('lecture.destroy', [$modul->slug, $key->urutan])}}">
                                        @csrf
                                        <input type="hidden" name="_method" value="DELETE" />
                                        <button class="btn btn-sm btn-danger del-btn" type="button" data-toggle="modal" data-target="#modal-del{{$key->urutan}}">Delete</button>
                                        <div id="modal-del{{$key->urutan}}" class="modal fade" tabindex="-1" role="dialog">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title">Hapus Data</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p class="text-wrap">Anda yakin ingin menghapus Materi pada {{ $modul->slug }} dengan urut : {{$key->urutan}} ?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="submit" class="btn btn-primary">Ya</button>
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </li>
                            </ul>
                        </td>
                    </tr>
                    @endforeach
                    @endif
                    @if(Auth::user()->hasRole('admin') || Auth::user()->hasRole('dosen'))
                    <tr id="add-link">
                        <th scope="row" colspan="4" style="font-size: 1rem !important;">
                            <a href="{{ route('lecture.create', $modul->slug) }}"><i class="fas fa-plus mr-2"></i>Tambah Materi</a>
                        </th>
                    </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
</div>

resources/views/func/lihatKelas.blade.php
@extends('layouts.app')

@section('content')
<header>
</header>
<article class="card-post my-5">
    <div class="container">
        @if(\Session::has('success'))
        <div class="alert alert-success">
            <p class="m-0">{{\Session::get('success')}}</p>
        </div>
        @endif
        <div class="row">
            <div class="col-12">
                <div class="main-card mb-3 card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-8">
                                <h3 class="card-title">Tabel Kelas</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('kelas.create') }}" class="btn btn-sm btn-primary">Add</a>
                            </div>
                        </div>
                        <div class="table-responsive">
                        <table id="table" class="mb-0 table align-items-center table-bordered">
                            <thead class="thead-light">
                                <tr>
                                    <th>No</th>
                                    <th>Title</th>
                                    <th>Dosen</th>
                                    <th>Sessions</th>
                                    <th>Participant</th>
                                    <th>Description</th>
                                    <th>Token</th>
                                    <th>Status</th>
                                    <th>Publish</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if($kelas->isEmpty())
                                <tr>
                                    <td id="deflection" class="text-center" colspan="10">Hasil Tidak Ditemukan</td>
                                </tr>
                                @else
                                @php
                                    $i = 1;
                                @endphp
                                @foreach($kelas as $key) 
                                <tr>   
                                    <td>{{$i++}}</td>
                                    <td>{{ $key->title }}</td>
                                    <td>{{$key->user->name}}</td>
                                    <td>{{ $key->sessions_count }} of {{ $key->sessions }}</td>
                                    <td>{{ $key->user_joined_count }}</td>
                                    <td>{{ strip_tags(substr($key->desc, 0, 35)) }}</td>
                                    <td>{{$key->token}}</td>
                                    <td>
                                        @if($key->status == '1')
                                            Dipublikasikan
                                        @else
                                            Disembunyikan
                                        @endif
                                    </td>
                                    <td>
                                        <ul>
                                            <li>
                                                <form action="{{ route('kelas.status') }}" method="POST" enctype="multipart/form-data">
                                                    @csrf
                                                    <input class="mb-1" type="hidden" name="id" value="{{ $key->id }}">
                                                    <input type="hidden" name="status" value="1">
                                                    <button type="submit" class="btn btn-sm btn-default" {{ $key->status == '1' ? 'disabled' : '' }}><i class="fa fa-check" aria-hidden="true"></i></button>
                                                </form>
                                            </li>
                                            <li>
                                                <form action="{{ route('kelas.status') }}" method="POST" enctype="multipart/form-data">
                                                    @csrf
                                                    <input type="hidden" name="id" value="{{ $key->id }}">
                                                    <input type="hidden" name="status" value="0">
                                                    <button type="submit" class="btn btn-sm btn-default" {{ $key->status == '0' ? 'disabled' : '' }}><i class="fa fa-eye-slash" aria-hidden="true"></i></button>
                                                </form>
                                            </li>
                                        </ul>
                                    </td>
                                    <td>
                                        <ul>
                                            <li>
                                                <a class="btn btn-sm btn-info" href="{{ route('kelas.show', $key->id) }}">Show</a>
                                            </li>
                                            <li>
                                                <a class="btn btn-sm btn-success" href="{{ route('kelas.edit', $key->id) }}">Edit</a>
                                            </li>
                                            <li>
                                                <form method="POST" action="{{ route('kelas.destroy', $key->id) }}">
                                                    @csrf
                                                    <input type="hidden" name="_method" value="DELETE" />
                                                    <button class="btn btn-sm btn-danger del-btn" type="button" data-toggle="modal" data-target="#modal-del{{$key->id}}">Delete</button>
                                                    <div id="modal-del{{$key->id}}" class="modal fade" tabindex="-1" role="dialog">
                                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title">Hapus Data</h5>
                                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <p>Anda yakin ingin menghapus kelas dengan ID : {{$key->id}} ?</p>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="submit" class="btn btn-primary">Ya</button>
                                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>  
                                @endforeach
                                @endif
                            </tbody>
                        </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>
@endsection